FROM gradle:7.5.1-jdk17-alpine AS builder
WORKDIR /workspace/app
COPY build.gradle settings.gradle ./
COPY src src

RUN gradle build -x test

FROM eclipse-temurin:17-alpine
WORKDIR /app

ARG APP_PORT=8000
ARG PG_USER=admin
ARG PG_PASSWORD=admin
ARG PG_DATABASE=cms-db
ARG PG_HOST=localhost
ARG PG_PORT=5431
ARG KEYCLOAK_DB=keycloak-db
ARG KEYCLOAK_DB_USER=admin
ARG KEYCLOAK_DB_PASSWORD=admin
ARG KEYCLOAK_DB_PORT=5432
ARG KEYCLOAK_DB_HOST=localhost
ARG KEYCLOAK_PORT=8080
ARG KEYCLOAK_ADMIN_USER=admin
ARG KEYCLOAK_ADMIN_PASSWORD=password

ENV APP_PORT=$APP_PORT
ENV PG_USER=$PG_USER
ENV PG_PASSWORD=$PG_PASSWORD
ENV PG_DATABASE=$PG_DATABASE
ENV PG_HOST=$PG_HOST
ENV PG_PORT=$PG_PORT
ENV KEYCLOAK_DB=$KEYCLOAK_DB
ENV KEYCLOAK_DB_USER=$KEYCLOAK_ADMIN_USER
ENV KEYCLOAK_DB_PASSWORD=$KEYCLOAK_DB_PASSWORD
ENV KEYCLOAK_DB_PORT=$KEYCLOAK_DB_PORT
ENV KEYCLOAK_DB_HOST=$KEYCLOAK_DB_HOST
ENV KEYCLOAK_PORT=$KEYCLOAK_PORT
ENV KEYCLOAK_ADMIN_USER=$KEYCLOAK_ADMIN_USER
ENV KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD

COPY --from=builder /workspace/app/build/libs/choose-my-snooze-0.0.1.jar .
EXPOSE 8080
EXPOSE 5431
EXPOSE $PORT
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "choose-my-snooze-0.0.1.jar"]