version: "3.1"
services:
  db:
    container_name: app-db
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}

  keycloak-db:
    container_name: keycloak-db
    image: bitnami/postgresql:latest
    networks:
      - keycloak
    volumes:
      - keycloak_data:/bitnami/postgresql
    ports:
      - "${KEYCLOAK_DB_PORT}"
    environment:
      - POSTGRESQL_USERNAME=${KEYCLOAK_DB_USER}
      - POSTGRESQL_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRESQL_DATABASE=${KEYCLOAK_DB}

# Need to do a realm import as everything breaks if the realm isnt set up
  keycloak:
    container_name: keycloak-server
    image: docker.io/bitnami/keycloak:latest
    networks:
      - keycloak
    depends_on:
      - keycloak-db
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    environment:
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DB}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DB}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DB_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}


volumes:
  pg_data:
  keycloak_data:

networks:
  keycloak: