version: "3.1"
services:
  cys-app:
    container_name: app
    image: cms-app:latest
    network_mode: host
    restart: on-failure
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - keycloak

  db:
    container_name: db
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}

  keycloak-db:
    container_name: keycloak-db
    image: bitnami/postgresql:latest
    networks:
      - keycloak
    volumes:
      - keycloak_data:/bitnami/postgresql
    ports:
      - "${KEYCLOAK_DB_PORT}"
    environment:
      - POSTGRESQL_USERNAME=${KEYCLOAK_DB_USER}
      - POSTGRESQL_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRESQL_DATABASE=${KEYCLOAK_DB}

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:latest
    networks:
      - keycloak
    depends_on:
      - keycloak-db
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    environment:
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DB}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DB}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DB_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}


volumes:
  pg_data:
  keycloak_data:

networks:
  keycloak:
