---
spring:
  config:
    activate:
      on-profile: prod
  name: prod-yaml
  environment: production
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${env.PGHOST}:${env.PGPORT}/${env.PGDATABASE}
    username: ${env.PGUSER}
    password: ${env.PGPASSWORD}

  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "health"


---
spring:
  config:
    activate:
      on-profile: test
  name: test-yaml
  environment: testing
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
  datasource:
    username: "sa"
    url: jdbc:h2:mem:testdb
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop